server:
  port: 8090
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:banking
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2-ui
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: 'true'
  http:
    encoding:
      force: 'true'
  resources:
    add-mappings: 'false'

keycloak:
  auth-server-url: http://localhost:8080
  credentials:
    secret: J2CORr0VDTgXtFStLd3LVhKhiSd4lDvR
  realm: banking-service
  bearer-only: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: none
  resource: banking-service-client


