version: '3.0'
services:
  account-postgresql:
    image: postgres:13.4
    # volumes:
    #   - ~/volumes/jhipster/account/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=account
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:5432:5432"
